POST http://localhost:3000/hfapi/token HTTP/1.1

###

POST http://localhost:3000/hfapi/getall HTTP/1.1


###

POST http://localhost:3000/dbapi/findmatches HTTP/1.1
content-type: application/json

{
    "ingredients": ["Creamy Chicken and Wild Rice Soup","Garlic Bread"]
}

###

GET http://localhost:3000/dbapi/allingredients HTTP/1.1

###

POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "email": "noreply@juncafe.com"
}

###

POST http://localhost:3000/login/authenticate HTTP/1.1
content-type: application/json

{
    "code": "651713",
    "email": "noreply@juncafe.com"
}

###

POST http://localhost:3000/session/create HTTP/1.1
content-type: application/json

{
    "email": "noreply@juncafe.com"
}